/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PageType = IDL.Variant({
  'habit' : IDL.Null,
  'timetracker' : IDL.Null,
  'normal' : IDL.Null,
  'plain' : IDL.Null,
});
export const Habit = IDL.Record({
  'goal' : IDL.Nat,
  'name' : IDL.Text,
  'frequency' : IDL.Nat,
});
export const Time = IDL.Int;
export const DiaryEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'pageType' : PageType,
  'timestamp' : Time,
});
export const Milestone = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'category' : IDL.Variant({
    'day' : IDL.Null,
    'month' : IDL.Null,
    'week' : IDL.Null,
    'year' : IDL.Null,
  }),
});
export const HabitTracker = IDL.Record({
  'completions' : IDL.Vec(Time),
  'habits' : IDL.Vec(Habit),
});
export const DiaryData = IDL.Record({
  'entries' : IDL.Vec(DiaryEntry),
  'habitTracker' : HabitTracker,
  'milestones' : IDL.Vec(Milestone),
});

export const idlService = IDL.Service({
  'addDiaryEntry' : IDL.Func([IDL.Text, PageType], [], []),
  'addHabit' : IDL.Func([Habit], [], []),
  'addMilestone' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'day' : IDL.Null,
          'month' : IDL.Null,
          'week' : IDL.Null,
          'year' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'completeHabit' : IDL.Func([IDL.Nat], [], []),
  'getDiaryEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
  'loadDiaryData' : IDL.Func([], [IDL.Opt(DiaryData)], ['query']),
  'saveDiaryData' : IDL.Func([DiaryData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PageType = IDL.Variant({
    'habit' : IDL.Null,
    'timetracker' : IDL.Null,
    'normal' : IDL.Null,
    'plain' : IDL.Null,
  });
  const Habit = IDL.Record({
    'goal' : IDL.Nat,
    'name' : IDL.Text,
    'frequency' : IDL.Nat,
  });
  const Time = IDL.Int;
  const DiaryEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'pageType' : PageType,
    'timestamp' : Time,
  });
  const Milestone = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'category' : IDL.Variant({
      'day' : IDL.Null,
      'month' : IDL.Null,
      'week' : IDL.Null,
      'year' : IDL.Null,
    }),
  });
  const HabitTracker = IDL.Record({
    'completions' : IDL.Vec(Time),
    'habits' : IDL.Vec(Habit),
  });
  const DiaryData = IDL.Record({
    'entries' : IDL.Vec(DiaryEntry),
    'habitTracker' : HabitTracker,
    'milestones' : IDL.Vec(Milestone),
  });
  
  return IDL.Service({
    'addDiaryEntry' : IDL.Func([IDL.Text, PageType], [], []),
    'addHabit' : IDL.Func([Habit], [], []),
    'addMilestone' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'day' : IDL.Null,
            'month' : IDL.Null,
            'week' : IDL.Null,
            'year' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'completeHabit' : IDL.Func([IDL.Nat], [], []),
    'getDiaryEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
    'loadDiaryData' : IDL.Func([], [IDL.Opt(DiaryData)], ['query']),
    'saveDiaryData' : IDL.Func([DiaryData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };