/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiaryData {
  'entries' : Array<DiaryEntry>,
  'habitTracker' : HabitTracker,
  'milestones' : Array<Milestone>,
}
export interface DiaryEntry {
  'id' : bigint,
  'content' : string,
  'pageType' : PageType,
  'timestamp' : Time,
}
export interface Habit {
  'goal' : bigint,
  'name' : string,
  'frequency' : bigint,
}
export interface HabitTracker {
  'completions' : Array<Time>,
  'habits' : Array<Habit>,
}
export interface Milestone {
  'title' : string,
  'date' : Time,
  'category' : { 'day' : null } |
    { 'month' : null } |
    { 'week' : null } |
    { 'year' : null },
}
export type PageType = { 'habit' : null } |
  { 'timetracker' : null } |
  { 'normal' : null } |
  { 'plain' : null };
export type Time = bigint;
export interface _SERVICE {
  'addDiaryEntry' : ActorMethod<[string, PageType], undefined>,
  'addHabit' : ActorMethod<[Habit], undefined>,
  'addMilestone' : ActorMethod<
    [
      string,
      { 'day' : null } |
        { 'month' : null } |
        { 'week' : null } |
        { 'year' : null },
    ],
    undefined
  >,
  'completeHabit' : ActorMethod<[bigint], undefined>,
  'getDiaryEntries' : ActorMethod<[], Array<DiaryEntry>>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getMilestones' : ActorMethod<[], Array<Milestone>>,
  'loadDiaryData' : ActorMethod<[], [] | [DiaryData]>,
  'saveDiaryData' : ActorMethod<[DiaryData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];