/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DiaryData {
    entries: Array<DiaryEntry>;
    habitTracker: HabitTracker;
    milestones: Array<Milestone>;
}
export type Time = bigint;
export interface DiaryEntry {
    id: bigint;
    content: string;
    pageType: PageType;
    timestamp: Time;
}
export interface Habit {
    goal: bigint;
    name: string;
    frequency: bigint;
}
export interface HabitTracker {
    completions: Array<Time>;
    habits: Array<Habit>;
}
export interface Milestone {
    title: string;
    date: Time;
    category: Variant_day_month_week_year;
}
export enum PageType {
    habit = "habit",
    timetracker = "timetracker",
    normal = "normal",
    plain = "plain"
}
export enum Variant_day_month_week_year {
    day = "day",
    month = "month",
    week = "week",
    year = "year"
}
export interface backendInterface {
    addDiaryEntry(content: string, pageType: PageType): Promise<void>;
    addHabit(habit: Habit): Promise<void>;
    addMilestone(title: string, category: Variant_day_month_week_year): Promise<void>;
    completeHabit(habitIndex: bigint): Promise<void>;
    getDiaryEntries(): Promise<Array<DiaryEntry>>;
    getHabits(): Promise<Array<Habit>>;
    getMilestones(): Promise<Array<Milestone>>;
    loadDiaryData(): Promise<DiaryData | null>;
    saveDiaryData(data: DiaryData): Promise<void>;
}
import type { DiaryData as _DiaryData, DiaryEntry as _DiaryEntry, HabitTracker as _HabitTracker, Milestone as _Milestone, PageType as _PageType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDiaryEntry(arg0: string, arg1: PageType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDiaryEntry(arg0, to_candid_PageType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDiaryEntry(arg0, to_candid_PageType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addHabit(arg0: Habit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHabit(arg0);
            return result;
        }
    }
    async addMilestone(arg0: string, arg1: Variant_day_month_week_year): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilestone(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilestone(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeHabit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeHabit(arg0);
            return result;
        }
    }
    async getDiaryEntries(): Promise<Array<DiaryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiaryEntries();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiaryEntries();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits();
            return result;
        }
    }
    async getMilestones(): Promise<Array<Milestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestones();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestones();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async loadDiaryData(): Promise<DiaryData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loadDiaryData();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadDiaryData();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDiaryData(arg0: DiaryData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDiaryData(to_candid_DiaryData_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDiaryData(to_candid_DiaryData_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DiaryData_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiaryData): DiaryData {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_DiaryEntry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiaryEntry): DiaryEntry {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Milestone_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Milestone): Milestone {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PageType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageType): PageType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiaryData]): DiaryData | null {
    return value.length === 0 ? null : from_candid_DiaryData_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: _Time;
    category: {
        day: null;
    } | {
        month: null;
    } | {
        week: null;
    } | {
        year: null;
    };
}): {
    title: string;
    date: Time;
    category: Variant_day_month_week_year;
} {
    return {
        title: value.title,
        date: value.date,
        category: from_candid_variant_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_DiaryEntry>;
    habitTracker: _HabitTracker;
    milestones: Array<_Milestone>;
}): {
    entries: Array<DiaryEntry>;
    habitTracker: HabitTracker;
    milestones: Array<Milestone>;
} {
    return {
        entries: from_candid_vec_n4(_uploadFile, _downloadFile, value.entries),
        habitTracker: value.habitTracker,
        milestones: from_candid_vec_n9(_uploadFile, _downloadFile, value.milestones)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    pageType: _PageType;
    timestamp: _Time;
}): {
    id: bigint;
    content: string;
    pageType: PageType;
    timestamp: Time;
} {
    return {
        id: value.id,
        content: value.content,
        pageType: from_candid_PageType_n7(_uploadFile, _downloadFile, value.pageType),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: null;
} | {
    month: null;
} | {
    week: null;
} | {
    year: null;
}): Variant_day_month_week_year {
    return "day" in value ? Variant_day_month_week_year.day : "month" in value ? Variant_day_month_week_year.month : "week" in value ? Variant_day_month_week_year.week : "year" in value ? Variant_day_month_week_year.year : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    habit: null;
} | {
    timetracker: null;
} | {
    normal: null;
} | {
    plain: null;
}): PageType {
    return "habit" in value ? PageType.habit : "timetracker" in value ? PageType.timetracker : "normal" in value ? PageType.normal : "plain" in value ? PageType.plain : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiaryEntry>): Array<DiaryEntry> {
    return value.map((x)=>from_candid_DiaryEntry_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Milestone>): Array<Milestone> {
    return value.map((x)=>from_candid_Milestone_n10(_uploadFile, _downloadFile, x));
}
function to_candid_DiaryData_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiaryData): _DiaryData {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_DiaryEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiaryEntry): _DiaryEntry {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Milestone_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Milestone): _Milestone {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PageType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageType): _PageType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<DiaryEntry>;
    habitTracker: HabitTracker;
    milestones: Array<Milestone>;
}): {
    entries: Array<_DiaryEntry>;
    habitTracker: _HabitTracker;
    milestones: Array<_Milestone>;
} {
    return {
        entries: to_candid_vec_n18(_uploadFile, _downloadFile, value.entries),
        habitTracker: value.habitTracker,
        milestones: to_candid_vec_n21(_uploadFile, _downloadFile, value.milestones)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    pageType: PageType;
    timestamp: Time;
}): {
    id: bigint;
    content: string;
    pageType: _PageType;
    timestamp: _Time;
} {
    return {
        id: value.id,
        content: value.content,
        pageType: to_candid_PageType_n1(_uploadFile, _downloadFile, value.pageType),
        timestamp: value.timestamp
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: Time;
    category: Variant_day_month_week_year;
}): {
    title: string;
    date: _Time;
    category: {
        day: null;
    } | {
        month: null;
    } | {
        week: null;
    } | {
        year: null;
    };
} {
    return {
        title: value.title,
        date: value.date,
        category: to_candid_variant_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageType): {
    habit: null;
} | {
    timetracker: null;
} | {
    normal: null;
} | {
    plain: null;
} {
    return value == PageType.habit ? {
        habit: null
    } : value == PageType.timetracker ? {
        timetracker: null
    } : value == PageType.normal ? {
        normal: null
    } : value == PageType.plain ? {
        plain: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_day_month_week_year): {
    day: null;
} | {
    month: null;
} | {
    week: null;
} | {
    year: null;
} {
    return value == Variant_day_month_week_year.day ? {
        day: null
    } : value == Variant_day_month_week_year.month ? {
        month: null
    } : value == Variant_day_month_week_year.week ? {
        week: null
    } : value == Variant_day_month_week_year.year ? {
        year: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DiaryEntry>): Array<_DiaryEntry> {
    return value.map((x)=>to_candid_DiaryEntry_n19(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Milestone>): Array<_Milestone> {
    return value.map((x)=>to_candid_Milestone_n22(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
